# -*- coding: utf-8 -*-
"""MidTerm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uNV_hSTFH4E0M9a8DM7XrS7aSqTgi8U

##**2.1 Acquire, Clean, and Preprocess Data**
"""

from google.colab import drive
drive.mount('/content/drive')

"""(a) Data Acquisition
- Identify your data source: file-based (CSV, JSON), database, API, etc.
- Document how you obtained it. For example, if from an API, show the request.
"""

!pip install kagglehub

!ls

import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import os
# Download latest version
file_path = kagglehub.dataset_download("kanchana1990/adzuna-global-job-listings-2025")

print("Path to dataset files:", file_path)
# !ls {file_path}

"""##Check if file id loaded correctly."""

csv_path = os.path.join(file_path, "adzuna_global_job_listings_2025.csv")
df = pd.read_csv(csv_path)
print(df.head())

"""(b) Data Cleaning
- Tasks: Handle missing values, remove duplicates, correct invalid entries.
- Python Tools: pandas methods (isnull, dropna, fillna, etc.).
- Tips: Always justify your decisions, e.g., why dropping vs. imputing missing values.
"""

#checking missing values
df.isnull().sum()
missing_data_col = df.columns[df.isnull().sum()>0]

#checking duplicates
df.duplicated()
#show rows with duplicates
df[df.duplicated()]

#TODO: droping or filling missing data

"""(c) Data Preprocessing
- Requirement: Use at least 2 preprocessing techniques (scaling, encoding, feature engineering, etc.).
- Tips: Ensure numeric vs. categorical variables are appropriately transformed.

##**2.2 Perform Exploratory Data Analysis (EDA) and Visualize Key Insights**

(a) Exploratory Data Analysis
- Compute basic stats (mean, median, std, etc.).
- Identify correlations, outliers, or data imbalances.
- Use pandas describe(), info(), corr() for an overview.
"""



"""(b) Data Visualization
- Requirement: At least 3 different visualization techniques (histogram, scatter plot, box plot, heatmap, etc.).
- Tips: Use clear labels, titles, and legends. Let visuals drive your EDA narrative.

"""



"""##**2.3 Build and Evaluate a Machine Learning Model**

(a) Model Building
- Requirement: At least 2 different ML algorithms (e.g., Logistic Regression, Random Forest, Linear Regression, etc.).
- Tips: Match the algorithm type to your target variable (classification vs. regression).
"""



"""(b) Model Evaluation
- Requirement: At least 2 different evaluation metrics (accuracy, precision/recall, F1, RMSE, MAE, etc.).
- Tips: Present numeric results and interpret them in plain English.
Consider basic hyperparameter tuning.

"""



# Load the latest version
df = pd.read_csv(
  "adzuna_global_job_listings_2025.csv"
)

print("First 5 records:", df.head())

